# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
          touch ./env.xcconfig
          echo ${{ secrets.API_URL }} >> ./env.xcconfig
          pod install --repo-update --clean-install
          xcodebuild clean test -project HANE24.xcodeproj -scheme 24HANE -destination 'platform=iOS simulator,name=iPhone 14 Pro,OS=latest' -target 24HANE
    - name: Run Swiftlint
      run: swiftlint --config .swiftlint.yml
    - name: Run tests
      run: swift test -v
