# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
          ls -lra
          pod install --repo-update --clean-install
          xcodebuild clean test -workspace HANE24.xcworkspace -scheme 24HANE -destination 'platform=iOS simulator,name=iPhone 15 Pro,OS=latest'
    - name: Run Swiftlint
      run: swiftlint --config .swiftlint.yml
    - name: Run tests
      run: swift test -v
