# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@master
      env:
        DIFF_BASE: ${{ github.base_ref }}
    - name: Run Test
      run: xcodebuild test clean \
            -workspace "HANE24.xcworkspace" \
            -scheme 24HANE \
            -destination 'platform=iOS simulator,name=iPhone 14 Pro,OS=latest' \
            -configuration=DEBUG
